### ISSUE TITLE
Paradise Bahamas (s3 Vision864)

### ISSUE THREAD

**Issue by Nikos74** [OBattler/86Box#39] opened 2016-11-14 10:29 UTC
Paradise Bahamas (s3 Vision864) in 86box (build 270 and later) has problems in windows 98SE.
After windows loading i get this screen......
![sample](https://cloud.githubusercontent.com/assets/23450515/20261276/1c3b0c28-aa6e-11e6-8c28-fc81f2b9afd2.JPG)

This is from build 282
No arrow on screen and all icons looks weird,
Maybe this problem in in other cards too.
Just have a check.
Thank you.

**Comment by MoochMcGee** [comment] 2016-12-04 20:24
That kinda looks like the PCI handling isn't quite right. It's as if the blitter is working, but it's not really fed with much.

**Comment by OBattler** [comment] 2018-01-16 07:25
Try the latest 86Box, this might incidentally have been caused by the palette write-beyond-array-boundaries bug that Sarah fixed for the Vision 864's in PCem and that I have applied to 86Box a while ago.

**Comment by OBattler** [comment] 2018-01-23 23:06
In fact, I just remembered I tested this card on this OS last year and it worked fine, so closing this issue as fixed.

**Closed by OBattler** 2018-01-23 23:06 UTC
